name: Deploy to AWS (Code2Cloud)

on:
  push:
    branches:
      - code2cloud-setup

jobs:
  deploy:
    name: Build & Deploy to AWS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Setup AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      
      # Log in and push to Amazon ECR (Default)
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      
      - name: Build, tag, and push backend to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: code2cloud-app-backend
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Create repository if it doesn't exist
          aws ecr describe-repositories --repository-names $ECR_REPOSITORY 2>/dev/null || aws ecr create-repository --repository-name $ECR_REPOSITORY
          
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest backend
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
      
      - name: Build, tag, and push frontend to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: code2cloud-app-frontend
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Create repository if it doesn't exist
          aws ecr describe-repositories --repository-names $ECR_REPOSITORY 2>/dev/null || aws ecr create-repository --repository-name $ECR_REPOSITORY
          
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest frontend
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
      
      

      # Setup Terraform and Apply
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan -no-color

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve -no-color