name: CI/CD Pipeline Frontend

on:
  push:
    branches: [ "master" ]
    paths:
      - "frontend/**"
      - ".github/workflows/deploy-frontend.yml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/code2cloud-frontend:latest
          build-args: |
            VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}

      - name: Deploy to GCP Instance via SSH
        uses: appleboy/ssh-action@v1.0.3
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
        with:
          host: ${{ secrets.FRONTEND_GCP_INSTANCE_IP }}
          username: ubuntu
          key: ${{ secrets.FRONTEND_SSH_PRIVATE_KEY }}
          envs: DOCKERHUB_USER, VITE_API_BASE_URL
          script: |
            # 1. Navigate to the project directory created by Terraform
            cd /home/ubuntu/app

            # 2. Recreate the .env file
            cat <<EOF > .env
            VITE_API_BASE_URL=$VITE_API_BASE_URL
            EOF

            # 3. Pull the latest image from Docker Hub
            # We use 'sudo' to avoid 'permission denied' errors connecting to the Docker socket
            sudo docker compose pull code2cloud-frontend

            # 4. Start the service in detached mode
            sudo docker compose up -d --remove-orphans code2cloud-frontend
